In [1]:
import numpy as np
import pandas as pd

### Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [3]:
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

### Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.


In [4]:
a1 = a.reshape(2,6)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [6]:
a2 = a.reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
a3 = a.reshape(6,2)
a3

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [9]:
a4 = a.reshape(4,3)
a4

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [14]:
a5 = a2.T
a5

array([[12, 16, 20],
       [13, 17, 21],
       [14, 18, 22],
       [15, 19, 23]])

### Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).


In [16]:
a6 = a.reshape(-1, 3)
a6

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [17]:
a7 = a.reshape(-1, 2)
a7

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [18]:
a8 = a.reshape(2 , -1)
a8

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [19]:
a9 = a.reshape(3 , -1)
a9

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [26]:
a10 = a.reshape(12 , -1)
a10

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

### Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


Нельзя, т.к. массив состоящий даже из одного столбца будет иметь доп индексацию (номер строки и столбца), а одномерный имеет индексацию с 1 индексом только

### Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [32]:
b = np.random.randn (3,4)
print(b)
print(b.size)
b=b.flatten()
print(b.size)

[[-0.34210456 -0.80070386  0.94108032 -0.93577868]
 [ 0.75983044 -0.99322316 -0.11025787  1.18726929]
 [-0.05717431 -0.68389318 -0.98791073  1.68339705]]
12
12


### Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [34]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

a - одномерный, b- двумерный массив

In [35]:
b = np.arange(20, 1, -2).reshape(1,10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

### Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [36]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [37]:
b = np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [39]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

### Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

Нет, т.к. это сингулярная матрица


In [54]:
a = np.arange(0, 12)
print(a)
A = a.reshape(4, 3)
print(A)
At = A.T
print(At)
B = np.dot(A, At)
print(B)
print(B.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
(4, 4)


array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

### Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [57]:
a = np.random.seed(42)

### Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [64]:
c = np.random.randint(0, 16, 16)
c

array([ 3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4,  3])

### Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [66]:
c = c.reshape(4, 4)
c

array([[ 3, 12, 14, 10],
       [ 7, 12,  4,  6],
       [ 9,  2,  6, 10],
       [10,  7,  4,  3]])

In [69]:
D = np.add(B, c*10)
D

array([[ 35, 134, 163, 132],
       [ 84, 170, 126, 182],
       [113, 106, 209, 312],
       [132, 192, 252, 332]])

In [72]:
print( np.linalg.det(D))
print( np.linalg.matrix_rank(D))
D_inv = np.linalg.inv(D)
print(D_inv)

21320000.000000034
4
[[-0.0421257  -0.04781989 -0.07423077  0.11272233]
 [ 0.00713133  0.01837899  0.00807692 -0.02050094]
 [-0.00235084 -0.03018386 -0.02807692  0.04386679]
 [ 0.01440901  0.03129456  0.04615385 -0.06324578]]


### Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [88]:
D_inv = np.where (D_inv<0, 0, 1)
D_inv
# Не понимаю, почему здесь это происходит

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])